package com.newline.serialport.ops;

public enum EN_CMD_OPS_TO_ANDROID {
    COTA_START_TRANSFER,
    COTA_TRANSFER_FILE_NAME,
    COTA_TRANSFER_FILE_CONTENT,
    COTA_TRANSFER_FILE_COMPLETED,
    COTA_STOP_TRANSFER
}
